// @ts-check
import { defineConfig, passthroughImageService } from 'astro/config';

import tailwindcss from '@tailwindcss/vite';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';

const SITE_URL = 'https://kavovo.uk';
const SITEMAP_EXCLUSIONS = new Set(['/404/', '/search/', '/subscription-confirmed/']);

// https://astro.build/config
export default defineConfig({
  site: SITE_URL,
  trailingSlash: 'always',
  // Responsive variants are pre-generated by scripts/build-images.mjs and served
  // as plain files. Astro must not try to transform anything itself: the host
  // builds with its own adapter, where sharp cannot run, and Astro silently
  // falls back to a /_image endpoint that 404s on every photo.
  image: { service: passthroughImageService() },
  vite: {
    plugins: [tailwindcss()],
  },

  integrations: [
    react(),
    sitemap({ filter: (page) => !SITEMAP_EXCLUSIONS.has(new URL(page).pathname) }),
  ],
});
