// @ts-check
import { defineConfig, passthroughImageService } from 'astro/config';

import tailwindcss from '@tailwindcss/vite';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';

// Update when a custom domain is connected
const SITE_URL = 'https://coffee.ridkous.workers.dev';

// https://astro.build/config
export default defineConfig({
  site: SITE_URL,
  trailingSlash: 'always',
  // Responsive variants are pre-generated by scripts/build-images.mjs and served
  // as plain files. Astro must not try to transform anything itself: the host
  // builds with its own adapter, where sharp cannot run, and Astro silently
  // falls back to a /_image endpoint that 404s on every photo.
  image: { service: passthroughImageService() },
  vite: {
    plugins: [tailwindcss()],
  },

  integrations: [react(), sitemap()],
});
