// @ts-check
import { defineConfig, passthroughImageService } from 'astro/config';

import tailwindcss from '@tailwindcss/vite';
import { satteri } from '@astrojs/markdown-satteri';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';
import satteriRecipeStepIds from './src/lib/satteri-recipe-step-ids.mjs';
import { contentLastmod } from './src/lib/sitemap-lastmod.mjs';

const SITE_URL = 'https://kavovo.uk';
const LASTMOD = contentLastmod();
const SITEMAP_EXCLUSIONS = new Set([
  '/404/',
  '/offline/',
  '/search/',
  '/recipes/saved/',
  '/shop/',
  '/subscription-confirmed/',
]);

// https://astro.build/config
export default defineConfig({
  site: SITE_URL,
  trailingSlash: 'always',
  // Responsive variants are pre-generated by scripts/build-images.mjs and served
  // as plain files. Astro must not try to transform anything itself: the host
  // builds with its own adapter, where sharp cannot run, and Astro silently
  // falls back to a /_image endpoint that 404s on every photo.
  image: { service: passthroughImageService() },
  markdown: {
    processor: satteri({ hastPlugins: [satteriRecipeStepIds] }),
  },
  vite: {
    plugins: [tailwindcss()],
    build: {
      // `font-src 'self'` in public/_headers blocks data: URIs, so any font
      // small enough for Vite to inline is a font the browser then refuses to
      // load — it happened silently to Manrope's cyrillic-ext subset. Fonts
      // always stay real files; everything else keeps Vite's default rule.
      assetsInlineLimit: (filePath) =>
        /\.(?:woff2?|ttf|otf|eot)$/i.test(filePath) ? false : undefined,
    },
  },

  integrations: [
    react(),
    sitemap({
      filter: (page) => !SITEMAP_EXCLUSIONS.has(new URL(page).pathname),
      serialize(item) {
        const lastmod = LASTMOD[new URL(item.url).pathname];
        return lastmod ? { ...item, lastmod } : item;
      },
    }),
  ],
});
